[package]
name = "arch-into"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = []
arch-64 = ["arch-32"]
arch-32 = []
