[package]
name = "arch-into"
version = "0.0.1-alpha.1"
edition = "2021"
license = "MIT"
description = "safe type conversions between pointer-sized types (usize/isize) and types with fixed size"

[dependencies]

[features]
default = []
arch-64 = ["arch-32"]
arch-32 = []
